import { createRequire } from "node:module";
import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import PDFDocument from "pdfkit";
import yauzl from "yauzl";
import { ZipFile } from "yazl";
import type { CvDocument, LetterDocument } from "../../contracts/src/documents.js";

const require = createRequire(import.meta.url);
const regularFont = require.resolve("@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff");
const boldFont = require.resolve("@fontsource/noto-sans/files/noto-sans-latin-700-normal.woff");
const margins = { top: 48, right: 52, bottom: 48, left: 52 };

async function deterministicDocx(buffer: Buffer, generatedAt: string): Promise<Buffer> {
  const sourceTime = new Date(generatedAt);
  const archiveTime = new Date(
    sourceTime.getUTCFullYear(),
    sourceTime.getUTCMonth(),
    sourceTime.getUTCDate(),
    sourceTime.getUTCHours(),
    sourceTime.getUTCMinutes(),
    sourceTime.getUTCSeconds(),
  );
  const input = await yauzl.fromBufferPromise(buffer, {
    lazyEntries: true,
    validateEntrySizes: true,
    strictFileNames: true,
  });
  const entries: Array<{ name: string; data: Buffer | null }> = [];
  for await (const entry of input.eachEntry()) {
    if (entry.fileName.endsWith("/")) {
      entries.push({ name: entry.fileName, data: null });
      continue;
    }
    const chunks: Buffer[] = [];
    for await (const chunk of await input.openReadStreamPromise(entry))
      chunks.push(Buffer.from(chunk));
    let data = Buffer.concat(chunks);
    if (entry.fileName === "docProps/core.xml") {
      const timestamp = sourceTime.toISOString();
      const xml = data
        .toString("utf8")
        .replace(/(<dcterms:created[^>]*>)[^<]*(<\/dcterms:created>)/, `$1${timestamp}$2`)
        .replace(/(<dcterms:modified[^>]*>)[^<]*(<\/dcterms:modified>)/, `$1${timestamp}$2`);
      data = Buffer.from(xml, "utf8");
    }
    entries.push({ name: entry.fileName, data });
  }
  input.close();

  const output = new ZipFile();
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const options = { mtime: archiveTime, forceDosTimestamp: true };
    if (entry.data) output.addBuffer(entry.data, entry.name, options);
    else output.addEmptyDirectory(entry.name, options);
  }
  const chunks: Buffer[] = [];
  const complete = new Promise<Buffer>((resolve, reject) => {
    output.outputStream.on("data", (chunk: Buffer) => chunks.push(chunk));
    output.outputStream.on("error", reject);
    output.outputStream.on("end", () => resolve(Buffer.concat(chunks)));
  });
  output.end();
  return complete;
}

const heading = (text: string) =>
  new Paragraph({
    text,
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 180, after: 80 },
    keepNext: true,
  });
const body = (text: string, options: { bullet?: boolean; bold?: boolean } = {}) =>
  new Paragraph({
    children: [
      new TextRun({ text, ...(options.bold ? { bold: true } : {}), size: 20, font: "Noto Sans" }),
    ],
    ...(options.bullet ? { bullet: { level: 0 } } : {}),
    spacing: { after: 70, line: 260 },
    widowControl: true,
  });
const title = (text: string) =>
  new Paragraph({
    children: [new TextRun({ text, bold: true, size: 34, font: "Noto Sans" })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 80 },
  });
const documentOptions = (children: Paragraph[], subject: string) => ({
  creator: "OpenCareers",
  title: subject,
  subject,
  description: "Evidence-linked application document generated by OpenCareers.",
  keywords: "application, evidence-linked",
  lastModifiedBy: "OpenCareers",
  revision: 1,
  styles: {
    default: {
      document: { run: { font: "Noto Sans", size: 20 }, paragraph: { spacing: { line: 260 } } },
      heading1: {
        run: { font: "Noto Sans", size: 23, bold: true, color: "17324D" },
        paragraph: { spacing: { before: 180, after: 80 }, keepNext: true },
      },
    },
  },
  sections: [
    {
      properties: {
        page: {
          margin: { top: 680, right: 740, bottom: 680, left: 740 },
        },
      },
      children,
    },
  ],
});

export async function renderCvDocx(cv: CvDocument, generatedAt: string): Promise<Buffer> {
  const contact = [cv.identity.email, cv.identity.phone, ...cv.identity.links]
    .filter(Boolean)
    .join(" | ");
  const children: Paragraph[] = [
    title(cv.identity.fullName),
    new Paragraph({ text: contact, alignment: AlignmentType.CENTER, spacing: { after: 160 } }),
    heading("Profile"),
    body(cv.summary.text),
    body(cv.experience.professional.text),
    body(cv.experience.handsOn.text),
    heading("Professional Experience"),
  ];
  for (const entry of cv.employment) {
    children.push(body(`${entry.title} | ${entry.employer}`, { bold: true }));
    children.push(
      body(`${entry.start} - ${entry.end ?? "Present"} | ${entry.workload.replace("_", " ")}`),
    );
    children.push(...entry.bullets.map((claim) => body(claim.text, { bullet: true })));
  }
  if (cv.education.length) {
    children.push(heading("Education"));
    for (const item of cv.education) {
      children.push(body(`${item.qualification} | ${item.institution}`, { bold: true }));
      children.push(body(`${item.start} - ${item.end ?? "Present"}`));
    }
  }
  if (cv.skills.length) {
    children.push(heading("Skills"));
    children.push(body(cv.skills.map((claim) => claim.text.replace(/\.$/, "")).join(" | ")));
  }
  if (cv.languages.length) {
    children.push(heading("Languages"));
    children.push(body(cv.languages.map((claim) => claim.text.replace(/\.$/, "")).join(" | ")));
  }
  if (cv.projects.length) {
    children.push(heading("Selected Projects"));
    children.push(...cv.projects.map((claim) => body(claim.text, { bullet: true })));
  }
  return deterministicDocx(
    Buffer.from(await Packer.toBuffer(new Document(documentOptions(children, "Curriculum Vitae")))),
    generatedAt,
  );
}

export async function renderLetterDocx(
  letter: LetterDocument,
  candidateName: string,
  generatedAt: string,
): Promise<Buffer> {
  const children = [
    title(candidateName),
    body(`${letter.role} | ${letter.company}`, { bold: true }),
    body(letter.salutation),
    body(letter.opening),
    ...letter.contributions.map((claim) => body(claim.text)),
    body(letter.motivation),
    ...(letter.practical ? [body(letter.practical.text)] : []),
    body(letter.closing),
  ];
  return deterministicDocx(
    Buffer.from(
      await Packer.toBuffer(
        new Document(documentOptions(children, `Motivation letter - ${letter.role}`)),
      ),
    ),
    generatedAt,
  );
}

interface PdfWriter {
  document: PDFKit.PDFDocument;
  write(text: string, options?: { heading?: boolean; title?: boolean; bullet?: boolean }): void;
  finish(): Promise<Buffer>;
}

function pdfWriter(subject: string, generatedAt: string): PdfWriter {
  const chunks: Buffer[] = [];
  const timestamp = new Date(generatedAt);
  const document = new PDFDocument({
    size: "A4",
    margins,
    bufferPages: true,
    autoFirstPage: true,
    tagged: true,
    info: {
      Title: subject,
      Author: "OpenCareers",
      Subject: subject,
      Creator: "OpenCareers",
      Producer: "OpenCareers pdfkit 0.20.2",
      CreationDate: timestamp,
      ModDate: timestamp,
    },
  });
  document.registerFont("Noto", regularFont);
  document.registerFont("NotoBold", boldFont);
  document.on("data", (chunk: Buffer) => chunks.push(chunk));
  const write = (
    raw: string,
    options: { heading?: boolean; title?: boolean; bullet?: boolean } = {},
  ) => {
    const text = `${options.bullet ? "• " : ""}${raw}`;
    const size = options.title ? 17 : options.heading ? 11.5 : 10;
    const font = options.title || options.heading ? "NotoBold" : "Noto";
    const width = document.page.width - margins.left - margins.right;
    document.font(font).fontSize(size);
    const height = document.heightOfString(text, { width, lineGap: 2 });
    const gapBefore = options.heading ? 9 : options.title ? 0 : 2;
    const gapAfter = options.title ? 8 : options.heading ? 3 : 2;
    if (document.y + gapBefore + height + gapAfter > document.page.height - margins.bottom) {
      document.addPage();
    }
    document.moveDown(gapBefore / size);
    document.text(text, { width, lineGap: 2, paragraphGap: gapAfter, continued: false });
  };
  return {
    document,
    write,
    finish: () =>
      new Promise<Buffer>((resolve, reject) => {
        document.on("end", () => resolve(Buffer.concat(chunks)));
        document.on("error", reject);
        document.end();
      }),
  };
}

export async function renderCvPdf(cv: CvDocument, generatedAt: string): Promise<Buffer> {
  const writer = pdfWriter("Curriculum Vitae", generatedAt);
  writer.document.font("NotoBold").fontSize(17);
  writer.write(cv.identity.fullName, { title: true });
  writer.write(
    [cv.identity.email, cv.identity.phone, ...cv.identity.links].filter(Boolean).join(" | "),
  );
  writer.write("Profile", { heading: true });
  writer.write(cv.summary.text);
  writer.write(cv.experience.professional.text);
  writer.write(cv.experience.handsOn.text);
  writer.write("Professional Experience", { heading: true });
  for (const entry of cv.employment) {
    writer.write(`${entry.title} | ${entry.employer}`, { heading: true });
    writer.write(
      `${entry.start} - ${entry.end ?? "Present"} | ${entry.workload.replace("_", " ")}`,
    );
    for (const claim of entry.bullets) writer.write(claim.text, { bullet: true });
  }
  if (cv.education.length) {
    writer.write("Education", { heading: true });
    for (const item of cv.education) {
      writer.write(`${item.qualification} | ${item.institution}`, { heading: true });
      writer.write(`${item.start} - ${item.end ?? "Present"}`);
    }
  }
  if (cv.skills.length) {
    writer.write("Skills", { heading: true });
    writer.write(cv.skills.map((claim) => claim.text.replace(/\.$/, "")).join(" | "));
  }
  if (cv.languages.length) {
    writer.write("Languages", { heading: true });
    writer.write(cv.languages.map((claim) => claim.text.replace(/\.$/, "")).join(" | "));
  }
  if (cv.projects.length) {
    writer.write("Selected Projects", { heading: true });
    for (const claim of cv.projects) writer.write(claim.text, { bullet: true });
  }
  return writer.finish();
}

export async function renderLetterPdf(
  letter: LetterDocument,
  candidateName: string,
  generatedAt: string,
): Promise<Buffer> {
  const writer = pdfWriter(`Motivation letter - ${letter.role}`, generatedAt);
  writer.write(candidateName, { title: true });
  writer.write(`${letter.role} | ${letter.company}`, { heading: true });
  writer.write(letter.salutation);
  writer.write(letter.opening);
  for (const claim of letter.contributions) writer.write(claim.text);
  writer.write(letter.motivation);
  if (letter.practical) writer.write(letter.practical.text);
  writer.write(letter.closing);
  return writer.finish();
}
